phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=468656523255.dkr.ecr.us-east-1.amazonaws.com/locations
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
artifacts:
    files: imagedefinitions.json